In [2]:
import sqlite3
from pathlib import Path
import pandas as pd

In [3]:
current_dir = Path.cwd()
data_dir = Path(current_dir, 'data.philiplessner.com')
path2processed = data_dir /'log_processed.csv'

In [4]:
df = pd.read_csv(path2processed, parse_dates=['datetime'], dtype={'status_Code': 'Int64', 'lat': 'Float64', 'lon': 'Float64'})

In [7]:
df.head()

,ip_address,datetime,request_type,endpoint,http_version,status_code,user_agent,Agent_Type,country,countryCode,region,regionName,city,zip,lat,lon,timezone
0,129.146.237.0,2026-07-12 11:11:43+00:00,GET,/blog/0,HTTP/1.1,200,Scrapy/2.16.0 (+https://scrapy.org),R,United States,US,AZ,Arizona,Phoenix,85008,33.4656,-111.9956,America/Phoenix
1,47.82.11.184,2026-07-12 11:12:43+00:00,GET,/robots.txt,HTTP/1.1,200,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,R,Singapore,SG,3,North West,Singapore,858877,1.35208,103.82,Asia/Singapore
2,47.82.11.184,2026-07-12 11:12:52+00:00,GET,/sitemap_news.xml.gz,HTTP/1.1,404,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,H,Singapore,SG,3,North West,Singapore,858877,1.35208,103.82,Asia/Singapore
3,40.77.167.144,2026-07-12 11:20:49+00:00,GET,/,HTTP/1.1,200,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",R,United States,US,VA,Virginia,Boydton,23917,36.677696,-78.37471,America/New_York
4,17.241.227.225,2026-07-12 11:26:03+00:00,GET,/photos/france,HTTP/1.1,200,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,R,United States,US,CA,California,Cupertino,95014,37.3322,-122.011,America/Los_Angeles

In [5]:
conn = sqlite3.connect(":memory")

In [6]:
df.to_sql("logs", conn, if_exists="replace", index=False)

3590

In [9]:
query = "SELECT * FROM logs WHERE Agent_Type == 'H'"
df_human = pd.read_sql_query(query, conn)

In [10]:
df_human.head()

,ip_address,datetime,request_type,endpoint,http_version,status_code,user_agent,Agent_Type,country,countryCode,region,regionName,city,zip,lat,lon,timezone
0,47.82.11.184,2026-07-12 11:12:52+00:00,GET,/sitemap_news.xml.gz,HTTP/1.1,404,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,H,Singapore,SG,3,North West,Singapore,858877,1.35208,103.8200,Asia/Singapore
1,154.159.252.207,2026-07-12 12:02:19+00:00,GET,/photos/australia,HTTP/1.1,200,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) ...,H,Kenya,KE,30,Nairobi County,Nairobi,9831,-1.28410,36.8155,Africa/Nairobi
2,171.250.162.196,2026-07-12 12:35:37+00:00,GET,/,HTTP/1.1,200,Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1)...,H,Vietnam,VN,SG,Ho Chi Minh,Ho Chi Minh City,700000,10.82200,106.6257,Asia/Ho_Chi_Minh
3,190.62.87.242,2026-07-12 13:21:14+00:00,GET,/blog/0,HTTP/1.1,200,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6...,H,El Salvador,SV,SS,San Salvador Department,San Salvador,NaN,13.69270,-89.1917,America/El_Salvador
4,138.84.33.34,2026-07-12 14:59:35+00:00,GET,/,HTTP/1.1,200,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,H,Chile,CL,RM,Santiago Metropolitan,Santiago,NaN,-33.44880,-70.6692,America/Santiago